{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "c01440fd",
   "metadata": {},
   "source": [
    "# Sistema de Votación por Tramos para Eurovisión 2025\n",
    "\n",
    "En este cuaderno se implementa un sistema de votación alternativo para Eurovisión basado en tramos de posiciones. En lugar de asignar puntos únicamente a los 10 primeros puestos, se otorgan puntos a los países según el bloque de posiciones en el que hayan quedado, siguiendo la siguiente escala:\n",
    "\n",
    "- Puesto 1: **12 puntos**\n",
    "- Puesto 2: **10 puntos**\n",
    "- Puesto 3: **8 puntos**\n",
    "- Puestos 4 y 5: **7 puntos**\n",
    "- Puestos 6 y 7: **6 puntos**\n",
    "- Puestos 8 y 9: **5 puntos**\n",
    "- Puestos 10, 11 y 12: **4 puntos**\n",
    "- Puestos 13, 14, 15 y 16: **3 puntos**\n",
    "- Puestos 17, 18, 19 y 20: **2 puntos**\n",
    "- Puestos 21, 22, 23 y 24: **1 punto**\n",
    "- Puestos 25 y 26: **0 puntos**\n",
    "\n",
    "Este sistema permite valorar de forma más amplia la posición obtenida por cada país, otorgando puntos a más participantes y diferenciando mejor los resultados intermedios.\n",
    "\n",
    "Además, se han generado los archivos `tabla_jurado_tramos.xlsx`, `tabla_publico_tramos.xlsx` y `tabla_total_tramos.xlsx` en formato Excel, disponibles para el análisis, así como los datos crudos en `data_cleaned.json`.\n",
    "\n",
    "\n",
    "Idea de Berme Rubio ([x.com/bermerubio](https://x.com/bermerubio))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a5f0599a",
   "metadata": {},
   "source": [
    "## Extracción de datos\n",
    "\n",
    "El archivo `data_cleaned.json` contiene los votos otorgados por cada país, tanto del jurado como del televoto, en formato estructurado. Estos datos serán la base para aplicar el sistema de puntuación por tramos."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "f838894c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Leídos 37 registros.\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "\n",
    "with open('data_cleaned.json', 'r', encoding='utf-8') as f:\n",
    "    data = json.load(f)\n",
    "    print(\"Leídos\", len(data), \"registros.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "b1911aaa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Países votantes: 37\n",
      "Países participantes: 26\n",
      "Países votantes que no llegaron a la final: 11\n"
     ]
    }
   ],
   "source": [
    "voting_countries = data.keys()\n",
    "participating_countries = [d['country'] for d in data['Croatia']['jury']]\n",
    "non_participating_countries = set(voting_countries) - set(participating_countries)\n",
    "print(\"Países votantes:\", len(voting_countries))\n",
    "print(\"Países participantes:\", len(participating_countries))\n",
    "print(\"Países votantes que no llegaron a la final:\", len(non_participating_countries))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "248ffeeb",
   "metadata": {},
   "source": [
    "## Verificación de datos\n",
    "\n",
    "El siguiente código comprueba que la suma de las posiciones asignadas por cada país es correcta, asegurando que no haya errores en los datos: los países que participan deben sumar 325 posiciones y los no participantes, 351."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "22e84e31",
   "metadata": {},
   "outputs": [],
   "source": [
    "for country in participating_countries:\n",
    "    for type in data[country]:\n",
    "        suma = sum(d['rank'] for d in data[country][type])\n",
    "        if suma != 325:\n",
    "            print(\"Error en el país\", country, \"tipo\", type, \"suma\", suma)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "c37c1e4b",
   "metadata": {},
   "outputs": [],
   "source": [
    "for country in non_participating_countries:\n",
    "    for type in data[country]:\n",
    "        suma = sum(d['rank'] for d in data[country][type])\n",
    "        if suma != 351:\n",
    "            print(\"Error en el país\", country, \"tipo\", type, \"suma\", suma)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ebafefb1",
   "metadata": {},
   "source": [
    "## Mapeo de puntos\n",
    "\n",
    "La siguiente función transforma la posición obtenida por cada país en puntos, aplicando el sistema de tramos definido al inicio del cuaderno."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "a75dcff3",
   "metadata": {},
   "outputs": [],
   "source": [
    "def rank_to_points(rank):\n",
    "    if rank == 1:\n",
    "        return 12\n",
    "    elif rank == 2:\n",
    "        return 10\n",
    "    elif rank == 3:\n",
    "        return 8\n",
    "    elif rank in (4, 5):\n",
    "        return 7\n",
    "    elif rank in (6, 7):\n",
    "        return 6\n",
    "    elif rank in (8, 9):\n",
    "        return 5\n",
    "    elif rank in (10, 11, 12):\n",
    "        return 4\n",
    "    elif rank in (13, 14, 15, 16):\n",
    "        return 3\n",
    "    elif rank in (17, 18, 19, 20):\n",
    "        return 2\n",
    "    elif rank in (21, 22, 23, 24):\n",
    "        return 1\n",
    "    else:\n",
    "        return 0"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "56eb5cc5",
   "metadata": {},
   "source": [
    "## Obtención de tablas de puntos para jurado y público\n",
    "\n",
    "Primero se define la función que genera la tabla de posiciones para cada país según los votos recibidos. Después, se aplicará el sistema de tramos para obtener las tablas de puntos tanto del jurado como del televoto."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "c5e37b15",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "def create_vote_table(vote_type):\n",
    "    table = {}\n",
    "    for voting_country, votes in data.items():\n",
    "        for vote in votes[vote_type]:\n",
    "            voted_country = vote['country']\n",
    "            rank = vote['rank']\n",
    "            if voted_country not in table:\n",
    "                table[voted_country] = {}\n",
    "            table[voted_country][voting_country] = rank\n",
    "    df = pd.DataFrame(table).T\n",
    "    df = df.sort_index().sort_index(axis=1)\n",
    "    return df"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "67892dc1",
   "metadata": {},
   "source": [
    "### Obtención de la tabla de puntos de jurado y guardado en Excel\n",
    "\n",
    "Se calcula la tabla de puntos asignados por el jurado a cada país aplicando el sistema de tramos, y se guarda en un archivo Excel para su posterior análisis."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "8ace95d5",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_jury = create_vote_table('jury')\n",
    "df_jury_points = df_jury.map(rank_to_points)\n",
    "total_jury_points = df_jury_points.sum(axis=1)\n",
    "total_jury_points.sort_values(ascending=False, inplace=True)\n",
    "df_jury_points['Total'] = total_jury_points\n",
    "df_jury_points.to_excel('tabla_jurado_tramos.xlsx')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d205034d",
   "metadata": {},
   "source": [
    "### Obtención de la tabla de puntos de televoto y guardado en Excel\n",
    "\n",
    "Se calcula la tabla de puntos asignados por el televoto a cada país aplicando el sistema de tramos, y se guarda en un archivo Excel para su posterior análisis."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "78965dd9",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_public = create_vote_table('public')\n",
    "df_public_points = df_public.map(rank_to_points)\n",
    "total_public_points = df_public_points.sum(axis=1)\n",
    "total_public_points.sort_values(ascending=False, inplace=True)\n",
    "df_public_points['Total'] = total_public_points\n",
    "df_public_points.to_excel('tabla_publico_tramos.xlsx')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9220bcf7",
   "metadata": {},
   "source": [
    "### Obtención de la tabla de puntos totales y guardado en Excel\n",
    "\n",
    "Se suman los puntos obtenidos por cada país en el jurado y en el televoto para obtener la clasificación final según el sistema de tramos. La tabla resultante se guarda en un archivo Excel para su análisis. Se muestran los 10 primeros y los 10 últimos."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "2d2727d5",
   "metadata": {},
   "outputs": [],
   "source": [
    "total_points = df_public_points + df_jury_points\n",
    "total_points.sort_values('Total', ascending=False, inplace=True)\n",
    "total_points.to_excel('tabla_total_tramos.xlsx')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4681a888",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Albania</th>\n",
       "      <th>Armenia</th>\n",
       "      <th>Australia</th>\n",
       "      <th>Austria</th>\n",
       "      <th>Azerbaijan</th>\n",
       "      <th>Belgium</th>\n",
       "      <th>Croatia</th>\n",
       "      <th>Cyprus</th>\n",
       "      <th>Czechia</th>\n",
       "      <th>Denmark</th>\n",
       "      <th>...</th>\n",
       "      <th>Portugal</th>\n",
       "      <th>San Marino</th>\n",
       "      <th>Serbia</th>\n",
       "      <th>Slovenia</th>\n",
       "      <th>Spain</th>\n",
       "      <th>Sweden</th>\n",
       "      <th>Switzerland</th>\n",
       "      <th>Ukraine</th>\n",
       "      <th>United Kingdom</th>\n",
       "      <th>Total</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Austria</th>\n",
       "      <td>14</td>\n",
       "      <td>15</td>\n",
       "      <td>12</td>\n",
       "      <td>0</td>\n",
       "      <td>13</td>\n",
       "      <td>17</td>\n",
       "      <td>16</td>\n",
       "      <td>14</td>\n",
       "      <td>7</td>\n",
       "      <td>11</td>\n",
       "      <td>...</td>\n",
       "      <td>14</td>\n",
       "      <td>9</td>\n",
       "      <td>18</td>\n",
       "      <td>20</td>\n",
       "      <td>13</td>\n",
       "      <td>16</td>\n",
       "      <td>14</td>\n",
       "      <td>11</td>\n",
       "      <td>12</td>\n",
       "      <td>505</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Estonia</th>\n",
       "      <td>8</td>\n",
       "      <td>17</td>\n",
       "      <td>12</td>\n",
       "      <td>13</td>\n",
       "      <td>15</td>\n",
       "      <td>15</td>\n",
       "      <td>18</td>\n",
       "      <td>10</td>\n",
       "      <td>9</td>\n",
       "      <td>10</td>\n",
       "      <td>...</td>\n",
       "      <td>9</td>\n",
       "      <td>14</td>\n",
       "      <td>17</td>\n",
       "      <td>14</td>\n",
       "      <td>8</td>\n",
       "      <td>12</td>\n",
       "      <td>11</td>\n",
       "      <td>11</td>\n",
       "      <td>12</td>\n",
       "      <td>450</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Israel</th>\n",
       "      <td>13</td>\n",
       "      <td>4</td>\n",
       "      <td>13</td>\n",
       "      <td>11</td>\n",
       "      <td>24</td>\n",
       "      <td>15</td>\n",
       "      <td>11</td>\n",
       "      <td>16</td>\n",
       "      <td>13</td>\n",
       "      <td>13</td>\n",
       "      <td>...</td>\n",
       "      <td>13</td>\n",
       "      <td>12</td>\n",
       "      <td>9</td>\n",
       "      <td>11</td>\n",
       "      <td>14</td>\n",
       "      <td>16</td>\n",
       "      <td>15</td>\n",
       "      <td>9</td>\n",
       "      <td>13</td>\n",
       "      <td>450</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Sweden</th>\n",
       "      <td>11</td>\n",
       "      <td>14</td>\n",
       "      <td>15</td>\n",
       "      <td>12</td>\n",
       "      <td>9</td>\n",
       "      <td>13</td>\n",
       "      <td>13</td>\n",
       "      <td>9</td>\n",
       "      <td>10</td>\n",
       "      <td>19</td>\n",
       "      <td>...</td>\n",
       "      <td>10</td>\n",
       "      <td>5</td>\n",
       "      <td>9</td>\n",
       "      <td>13</td>\n",
       "      <td>10</td>\n",
       "      <td>0</td>\n",
       "      <td>16</td>\n",
       "      <td>9</td>\n",
       "      <td>11</td>\n",
       "      <td>430</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Italy</th>\n",
       "      <td>13</td>\n",
       "      <td>7</td>\n",
       "      <td>4</td>\n",
       "      <td>13</td>\n",
       "      <td>13</td>\n",
       "      <td>10</td>\n",
       "      <td>19</td>\n",
       "      <td>9</td>\n",
       "      <td>8</td>\n",
       "      <td>11</td>\n",
       "      <td>...</td>\n",
       "      <td>20</td>\n",
       "      <td>17</td>\n",
       "      <td>7</td>\n",
       "      <td>24</td>\n",
       "      <td>10</td>\n",
       "      <td>7</td>\n",
       "      <td>20</td>\n",
       "      <td>15</td>\n",
       "      <td>5</td>\n",
       "      <td>399</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>France</th>\n",
       "      <td>16</td>\n",
       "      <td>22</td>\n",
       "      <td>6</td>\n",
       "      <td>10</td>\n",
       "      <td>5</td>\n",
       "      <td>11</td>\n",
       "      <td>6</td>\n",
       "      <td>15</td>\n",
       "      <td>10</td>\n",
       "      <td>5</td>\n",
       "      <td>...</td>\n",
       "      <td>10</td>\n",
       "      <td>9</td>\n",
       "      <td>15</td>\n",
       "      <td>8</td>\n",
       "      <td>12</td>\n",
       "      <td>9</td>\n",
       "      <td>14</td>\n",
       "      <td>6</td>\n",
       "      <td>6</td>\n",
       "      <td>367</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Greece</th>\n",
       "      <td>19</td>\n",
       "      <td>11</td>\n",
       "      <td>19</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>10</td>\n",
       "      <td>9</td>\n",
       "      <td>24</td>\n",
       "      <td>7</td>\n",
       "      <td>7</td>\n",
       "      <td>...</td>\n",
       "      <td>6</td>\n",
       "      <td>16</td>\n",
       "      <td>15</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>8</td>\n",
       "      <td>11</td>\n",
       "      <td>3</td>\n",
       "      <td>9</td>\n",
       "      <td>350</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Netherlands</th>\n",
       "      <td>9</td>\n",
       "      <td>10</td>\n",
       "      <td>5</td>\n",
       "      <td>10</td>\n",
       "      <td>8</td>\n",
       "      <td>11</td>\n",
       "      <td>6</td>\n",
       "      <td>12</td>\n",
       "      <td>9</td>\n",
       "      <td>4</td>\n",
       "      <td>...</td>\n",
       "      <td>11</td>\n",
       "      <td>7</td>\n",
       "      <td>7</td>\n",
       "      <td>9</td>\n",
       "      <td>14</td>\n",
       "      <td>13</td>\n",
       "      <td>11</td>\n",
       "      <td>6</td>\n",
       "      <td>4</td>\n",
       "      <td>334</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Finland</th>\n",
       "      <td>4</td>\n",
       "      <td>14</td>\n",
       "      <td>15</td>\n",
       "      <td>17</td>\n",
       "      <td>8</td>\n",
       "      <td>10</td>\n",
       "      <td>11</td>\n",
       "      <td>6</td>\n",
       "      <td>7</td>\n",
       "      <td>13</td>\n",
       "      <td>...</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>8</td>\n",
       "      <td>7</td>\n",
       "      <td>9</td>\n",
       "      <td>17</td>\n",
       "      <td>8</td>\n",
       "      <td>6</td>\n",
       "      <td>12</td>\n",
       "      <td>333</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Albania</th>\n",
       "      <td>0</td>\n",
       "      <td>6</td>\n",
       "      <td>9</td>\n",
       "      <td>9</td>\n",
       "      <td>10</td>\n",
       "      <td>9</td>\n",
       "      <td>12</td>\n",
       "      <td>8</td>\n",
       "      <td>6</td>\n",
       "      <td>5</td>\n",
       "      <td>...</td>\n",
       "      <td>11</td>\n",
       "      <td>11</td>\n",
       "      <td>7</td>\n",
       "      <td>11</td>\n",
       "      <td>9</td>\n",
       "      <td>12</td>\n",
       "      <td>13</td>\n",
       "      <td>8</td>\n",
       "      <td>7</td>\n",
       "      <td>332</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>10 rows × 38 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "             Albania  Armenia  Australia  Austria  Azerbaijan  Belgium  \\\n",
       "Austria           14       15         12        0          13       17   \n",
       "Estonia            8       17         12       13          15       15   \n",
       "Israel            13        4         13       11          24       15   \n",
       "Sweden            11       14         15       12           9       13   \n",
       "Italy             13        7          4       13          13       10   \n",
       "France            16       22          6       10           5       11   \n",
       "Greece            19       11         19        4           4       10   \n",
       "Netherlands        9       10          5       10           8       11   \n",
       "Finland            4       14         15       17           8       10   \n",
       "Albania            0        6          9        9          10        9   \n",
       "\n",
       "             Croatia  Cyprus  Czechia  Denmark  ...  Portugal  San Marino  \\\n",
       "Austria           16      14        7       11  ...        14           9   \n",
       "Estonia           18      10        9       10  ...         9          14   \n",
       "Israel            11      16       13       13  ...        13          12   \n",
       "Sweden            13       9       10       19  ...        10           5   \n",
       "Italy             19       9        8       11  ...        20          17   \n",
       "France             6      15       10        5  ...        10           9   \n",
       "Greece             9      24        7        7  ...         6          16   \n",
       "Netherlands        6      12        9        4  ...        11           7   \n",
       "Finland           11       6        7       13  ...         5           5   \n",
       "Albania           12       8        6        5  ...        11          11   \n",
       "\n",
       "             Serbia  Slovenia  Spain  Sweden  Switzerland  Ukraine  \\\n",
       "Austria          18        20     13      16           14       11   \n",
       "Estonia          17        14      8      12           11       11   \n",
       "Israel            9        11     14      16           15        9   \n",
       "Sweden            9        13     10       0           16        9   \n",
       "Italy             7        24     10       7           20       15   \n",
       "France           15         8     12       9           14        6   \n",
       "Greece           15         5      5       8           11        3   \n",
       "Netherlands       7         9     14      13           11        6   \n",
       "Finland           8         7      9      17            8        6   \n",
       "Albania           7        11      9      12           13        8   \n",
       "\n",
       "             United Kingdom  Total  \n",
       "Austria                  12    505  \n",
       "Estonia                  12    450  \n",
       "Israel                   13    450  \n",
       "Sweden                   11    430  \n",
       "Italy                     5    399  \n",
       "France                    6    367  \n",
       "Greece                    9    350  \n",
       "Netherlands               4    334  \n",
       "Finland                  12    333  \n",
       "Albania                   7    332  \n",
       "\n",
       "[10 rows x 38 columns]"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Primeras diez posiciones\n",
    "total_points.head(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9859bcb3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Albania</th>\n",
       "      <th>Armenia</th>\n",
       "      <th>Australia</th>\n",
       "      <th>Austria</th>\n",
       "      <th>Azerbaijan</th>\n",
       "      <th>Belgium</th>\n",
       "      <th>Croatia</th>\n",
       "      <th>Cyprus</th>\n",
       "      <th>Czechia</th>\n",
       "      <th>Denmark</th>\n",
       "      <th>...</th>\n",
       "      <th>Portugal</th>\n",
       "      <th>San Marino</th>\n",
       "      <th>Serbia</th>\n",
       "      <th>Slovenia</th>\n",
       "      <th>Spain</th>\n",
       "      <th>Sweden</th>\n",
       "      <th>Switzerland</th>\n",
       "      <th>Ukraine</th>\n",
       "      <th>United Kingdom</th>\n",
       "      <th>Total</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Norway</th>\n",
       "      <td>6</td>\n",
       "      <td>8</td>\n",
       "      <td>3</td>\n",
       "      <td>4</td>\n",
       "      <td>8</td>\n",
       "      <td>3</td>\n",
       "      <td>10</td>\n",
       "      <td>7</td>\n",
       "      <td>12</td>\n",
       "      <td>6</td>\n",
       "      <td>...</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "      <td>6</td>\n",
       "      <td>10</td>\n",
       "      <td>6</td>\n",
       "      <td>9</td>\n",
       "      <td>4</td>\n",
       "      <td>13</td>\n",
       "      <td>4</td>\n",
       "      <td>230</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Malta</th>\n",
       "      <td>2</td>\n",
       "      <td>10</td>\n",
       "      <td>14</td>\n",
       "      <td>11</td>\n",
       "      <td>7</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>5</td>\n",
       "      <td>7</td>\n",
       "      <td>5</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>5</td>\n",
       "      <td>6</td>\n",
       "      <td>2</td>\n",
       "      <td>8</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "      <td>5</td>\n",
       "      <td>11</td>\n",
       "      <td>206</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Armenia</th>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>5</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>4</td>\n",
       "      <td>8</td>\n",
       "      <td>6</td>\n",
       "      <td>5</td>\n",
       "      <td>...</td>\n",
       "      <td>4</td>\n",
       "      <td>3</td>\n",
       "      <td>7</td>\n",
       "      <td>2</td>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>204</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>United Kingdom</th>\n",
       "      <td>3</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "      <td>8</td>\n",
       "      <td>5</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>10</td>\n",
       "      <td>8</td>\n",
       "      <td>...</td>\n",
       "      <td>6</td>\n",
       "      <td>6</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "      <td>8</td>\n",
       "      <td>1</td>\n",
       "      <td>7</td>\n",
       "      <td>11</td>\n",
       "      <td>0</td>\n",
       "      <td>187</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Luxembourg</th>\n",
       "      <td>11</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>6</td>\n",
       "      <td>3</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>...</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>6</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>7</td>\n",
       "      <td>8</td>\n",
       "      <td>183</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Iceland</th>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "      <td>7</td>\n",
       "      <td>7</td>\n",
       "      <td>3</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>6</td>\n",
       "      <td>13</td>\n",
       "      <td>...</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>6</td>\n",
       "      <td>3</td>\n",
       "      <td>8</td>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "      <td>177</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Spain</th>\n",
       "      <td>11</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>6</td>\n",
       "      <td>4</td>\n",
       "      <td>6</td>\n",
       "      <td>5</td>\n",
       "      <td>2</td>\n",
       "      <td>3</td>\n",
       "      <td>...</td>\n",
       "      <td>9</td>\n",
       "      <td>5</td>\n",
       "      <td>6</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>7</td>\n",
       "      <td>6</td>\n",
       "      <td>1</td>\n",
       "      <td>5</td>\n",
       "      <td>174</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Denmark</th>\n",
       "      <td>4</td>\n",
       "      <td>3</td>\n",
       "      <td>9</td>\n",
       "      <td>10</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>5</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>4</td>\n",
       "      <td>6</td>\n",
       "      <td>1</td>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>13</td>\n",
       "      <td>167</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Portugal</th>\n",
       "      <td>5</td>\n",
       "      <td>6</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>9</td>\n",
       "      <td>2</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>6</td>\n",
       "      <td>2</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>7</td>\n",
       "      <td>2</td>\n",
       "      <td>6</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "      <td>9</td>\n",
       "      <td>9</td>\n",
       "      <td>4</td>\n",
       "      <td>166</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>San Marino</th>\n",
       "      <td>10</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>110</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>10 rows × 38 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                Albania  Armenia  Australia  Austria  Azerbaijan  Belgium  \\\n",
       "Norway                6        8          3        4           8        3   \n",
       "Malta                 2       10         14       11           7        2   \n",
       "Armenia               4        0          2        5           0        3   \n",
       "United Kingdom        3        4          5        8           5        2   \n",
       "Luxembourg           11        3          5        6           3        4   \n",
       "Iceland               4        2          7        7           3        3   \n",
       "Spain                11        4          5        3           6        4   \n",
       "Denmark               4        3          9       10           3        5   \n",
       "Portugal              5        6          0        2           9        2   \n",
       "San Marino           10        3          0        3           4        1   \n",
       "\n",
       "                Croatia  Cyprus  Czechia  Denmark  ...  Portugal  San Marino  \\\n",
       "Norway               10       7       12        6  ...         4           5   \n",
       "Malta                 2       5        7        5  ...         2           5   \n",
       "Armenia               4       8        6        5  ...         4           3   \n",
       "United Kingdom        2       2       10        8  ...         6           6   \n",
       "Luxembourg            2       5        3        5  ...         5           3   \n",
       "Iceland               5       4        6       13  ...         3           5   \n",
       "Spain                 6       5        2        3  ...         9           5   \n",
       "Denmark               2       2        5        0  ...         2           4   \n",
       "Portugal              3       5        6        2  ...         0           7   \n",
       "San Marino            2       4        1        0  ...         0           0   \n",
       "\n",
       "                Serbia  Slovenia  Spain  Sweden  Switzerland  Ukraine  \\\n",
       "Norway               6        10      6       9            4       13   \n",
       "Malta                6         2      8       4            2        5   \n",
       "Armenia              7         2      5       4            1        5   \n",
       "United Kingdom       4         2      8       1            7       11   \n",
       "Luxembourg           5         6      3       5            3        7   \n",
       "Iceland              3         6      3       8            5        4   \n",
       "Spain                6         2      0       7            6        1   \n",
       "Denmark              6         1      5       4            2        2   \n",
       "Portugal             2         6      4       2            9        9   \n",
       "San Marino           3         1      1       2            4        1   \n",
       "\n",
       "                United Kingdom  Total  \n",
       "Norway                       4    230  \n",
       "Malta                       11    206  \n",
       "Armenia                      5    204  \n",
       "United Kingdom               0    187  \n",
       "Luxembourg                   8    183  \n",
       "Iceland                      5    177  \n",
       "Spain                        5    174  \n",
       "Denmark                     13    167  \n",
       "Portugal                     4    166  \n",
       "San Marino                   0    110  \n",
       "\n",
       "[10 rows x 38 columns]"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Últimas 10 posiciones\n",
    "total_points.tail(10)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
